global:
  scrape_interval: 15s
  external_labels:
    monitor: 'codelab-monitor'
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'redis'
    scrape_interval: 5s
    static_configs:
    
      - targets: ['10.20.1.180:9121']

  - job_name: 'kafka'
    static_configs:
      - targets: ['10.20.1.180:9308','localhost:9308']

  - job_name: 'zookeeper'
    static_configs:
      - targets: ['10.20.1.180:9141']

